From:nfcore/base
Bootstrap:docker

%labels
    DESCRIPTION Singularity image containing all requirements for {{ cookiecutter.pipeline_name }} pipeline
    VERSION {{ cookiecutter.version }}

%environment
    PATH=/opt/conda/envs/nfcore-{{ cookiecutter.pipeline_slug }}-{{ cookiecutter.version }}/bin:$PATH
    export PATH

%files
    environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
