From:nfcore/base
Bootstrap:docker

%labels
    MAINTAINER {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
    DESCRIPTION Singularity image containing all requirements for {{ cookiecutter.pipeline_name }} pipeline
    VERSION {{ cookiecutter.version }}

%files
    environment.yml /

%post
    /opt/conda/bin/conda env update -n root -f /environment.yml
    /opt/conda/bin/conda clean -a
