# Markdownlint configuration file
default: true
line-length: false
no-duplicate-header:
    siblings_only: true
# tools only - the {{ jinja variables }} break URLs and cause this to error
no-bare-urls: false
# tools only - suppresses error messages for usage of $ in main README
commands-show-output: false
# Enable usage of nice HTML tags in output docs for pipeline template
MD033:
    allowed_elements: [details, summary]
