name: extract_viral_taxid
description: Extract viral taxids identified by Kraken2, Centrifuge, or DIAMOND classification
keywords:
  - taxid
  - virus
  - taxpasta
  - kraken2
  - centrifuge
  - diamond
input:
  - evalue_threshold:
      type: ["number", "integer"]
      description: An e-value threshold to filter the diamond classification result
  - phages_taxid:
      type: file
      description: A list of phage taxids to exclude from the extracted viral taxids
  - - meta:
        type: map
        description: |
          Groovy map containing sample information
          e.g. [ id:'test', single_end:false ]
    - taxpasta_standardised_profile:
        type: file
        description: Path to the taxpasta standardised profile
    - report:
        type: file
        description: |
          Path to the classifier report (Kraken2/Centrifuge) or TSV file (DIAMOND)
          containing the identified viral taxids
output:
  viral_taxid:
    - - meta:
          type: map
          description: |
            Groovy map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*viral_taxids.tsv":
          type: file
          description: Extracted viral taxid table
          pattern: "*viral_taxids.tsv"
authors:
  - "@LilyAnderssonLee"
