name: filter_blast
description: Use a custom python script to filter the blast(blastn/blastx) hits
keywards:
  - blastn
  - blastx
  - filter
  - summary
  - taxonomy

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - blast_hits:
      type: file
      description: Comma separated file containing blast hits
      pattern: "*.txt"
  - header:
      type: file
      description: A header file for blast hits. For instance 'qseqid,sseqid,slen,pident,qlen,length,qcovs,nident,evalue,bitscore,staxid,ssciname'.
      pattern: "*.txt"
output:
  - filtered_blast:
      type: file
      description: Filtered and summarized blast hits by taxid and subject Scientific Name
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@LilyAnderssonLee"
