---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "{{ component_name_underscore }}"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "{{ component }}":
      description: "{{ tool_description }}"
      homepage: "{{ tool_doc_url }}"
      documentation: "{{ tool_doc_url }}"
      tool_dev_url: "{{ tool_dev_url }}"
      doi: ""
      licence: {{ tool_licence }}
      identifier: {{ tool_identifier }}

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # CRAM
          - edam: "http://edamontology.org/format_3462" # SAM

output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{bam,cram,sam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
            - edam: "http://edamontology.org/format_2573" # CRAM
            - edam: "http://edamontology.org/format_3462" # SAM
  versions_{{ component }}:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "{{ component }}":
          type: string
          description: The name of the tool
      - "{{ component }} --version":
          type: string
          description: The version of the tool

topics:
  versions:
    - - process:
          type: string
          description: The process the versions were collected from
      - tool:
          type: string
          description: The tool name the version was collected for
      - version:
          type: string
          description: The version of the tool

authors:
  - "{{ author }}"
maintainers:
  - "{{ author }}"
