name: rm_empty_bam
description: |
  Remove empty BAM files and their corresponding BAI files.
  This occurs when none of the reads map to the reference genome.
keywards:
  - empty
  - BAM
input:
  - folder:
      type: path
      description: Path to the mapping folder
output:
  - folder:
      type: path
      description: Path stores the non-empty BAM and BAI files
authors:
  - "@LilyAnderssonLee"