repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.0

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.0"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/nf-core/tools
    rev: "3.1.0"
    hooks:
      - id: lint-pipeline
