name: subset_bam
description: Subset a BAM file by a list of taxid-associated reference accessions
keywords:
  - samtools
  - view
  - subset
  - bam
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM file aligned against pathogen genomes
        pattern: "*.{bam}"
    - bai:
        type: file
        description: BAM index file
        pattern: "*.{bai}"
  - taxid_accession:
      type: list
      description: A list of reference accessions associated with the selected taxid
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: BAM file subset to the selected accessions
          pattern: "*.{bam}"
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - "samtools --version |& sed '1!d ; s/samtools //'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - "samtools --version |& sed '1!d ; s/samtools //'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@LilyAnderssonLee"
