From:nfcore/base
Bootstrap:docker

%labels
    MAINTAINER {{ cookiecutter.author }}
    DESCRIPTION Singularity image containing all requirements for the {{ cookiecutter.name }} pipeline
    VERSION {{ cookiecutter.version }}

%environment
    PATH=/opt/conda/envs/{{ cookiecutter.name_noslash }}-{{ cookiecutter.version }}/bin:$PATH
    export PATH

%files
    environment.yml /

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
