# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: mapping_shortread
description: Build short-read mapping indexes, align reads with bowtie2, and generate BAM statistics
keywords:
  - bowtie2
  - mapping
  - short reads
  - bam
components:
  - bowtie2/build
  - fastq_align_bowtie2
  - pigz/uncompress
  - samtools/faidx
input:
  - ch_reads_reference:
      description: |
        Short reads paired with reference genomes.
        Structure: [ val(meta), path(reads), path(reference) ]
output:
  - index:
      description: |
        Bowtie2 index files.
        Structure: [ val(meta), path(index) ]
  - bam:
      description: |
        Sorted BAM alignment files.
        Structure: [ val(meta), path(bam) ]
  - bai:
      description: |
        BAM index files.
        Structure: [ val(meta), path(bai) ]
  - flagstat:
      description: |
        Samtools flagstat reports.
        Structure: [ val(meta), path(flagstat) ]
  - versions:
      description: |
        Files containing software versions.
        Structure: [ path(versions.yml) ]
  - mqc:
      description: |
        MultiQC-ready summary files.
authors:
  - "@LilyAnderssonLee"
maintainers:
  - "@LilyAnderssonLee"
