name: Test with Nextflow from source

on:
  workflow_dispatch: # Manual trigger
  schedule:
    # Run at 00:00 UTC on Monday, Wednesday, Friday (2:00 CEST)
    - cron: "0 0 * * 1,3,5"

jobs:
  test-with-nextflow-source:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false

    steps:
      - name: Check out Nextflow
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: nextflow-io/nextflow
          path: nextflow

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          architecture: x64
          cache: gradle
          cache-dependency-path: "nextflow/**/*.gradle*"
          java-version: "21"

      - name: Build Nextflow
        run: cd nextflow && make pack

      - name: Move Nextflow to local bin/
        run: |
          mkdir -p $HOME/.local/bin/
          mv nextflow/build/releases/nextflow*dist $HOME/.local/bin/nextflow
          chmod +x $HOME/.local/bin/nextflow
          nextflow -version

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        name: Check out nf-core/tools
        with:
          ref: dev

      # Set up nf-core/tools
      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install nf-core/tools
        run: uv sync

      - name: Create new pipeline
        run: uv run nf-core pipelines create -n testpipeline -d "This pipeline is for testing" -a "Testing McTestface"

      - name: Run new pipeline
        run: nextflow run nf-core-testpipeline -profile docker,test --outdir ./results

      - name: Send email on failure
        if: failure()
        uses: dsfx3d/action-aws-ses@a0daa3774d2bb09e2bcb512e55bdc3510b6102ef # v1.0.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
        with:
          to: ${{ secrets.NEXTFLOW_NIGHTLY_NOTIFICATION_EMAIL_ADDRESS }}
          from: core@nf-co.re
          subject: "Nextflow source test CI failed"
          body: |
            The Nextflow source test CI workflow failed!

            See the failed run here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
