name: Update Modules Template

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.x"

      - name: Install nf-core
        run: pip install nf-core

      - name: Update modules
        run: nf-core modules update --all
        working-directory: nf-core/pipeline-template

      - name: Update subworkflows
        run: nf-core subworkflows update --all
        working-directory: nf-core/pipeline-template

      # Commit the changes
      - name: Commit changes
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git add .
          git status
          git commit -m "[automated] Fix code linting"

      # Open a new PR to dev with the changes
      - name: Create PR
        run: |
          git checkout -b update-modules
          git push origin update-modules
          gh pr create --title "Update modules in template" --body "This PR updates the modules in the pipeline template" --base dev --head update-modules
