name: filter_consensus
description: Use a custom python script to filter the consensus
keywards:
  - samtools
  - consensus
  - filter

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - consensus:
      type: file
      description: Consensus FASTA file
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
  - consensus_min_bases:
      type: number
      description: "The minimum number of bases used to filter consensus sequences."
output:
  - filtered_consensus:
      type: file
      description: Filtered consensus sequences
      pattern: "*.fasta"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@LilyAnderssonLee"
